BaseURL = "https://nitishpuri.github.io/blog-hugo/"
languageCode = "en-us"
title = "Blog - Nitish Puri"
# theme = "mytheme"
theme = "hugo-bootstrap-5"
relativeURLS = true

[params]
author = "Nitish Puri"
description = "These are some notes."
logo = "https://www.mywebsite.com/images/logo.png"
images = ["/images/site-feature-image.jpg"]
# copyright = "Hugo template made with ❤ by Nitish"

[taxonomies]
  tag = "tags"
  category = "categories"


# Google analytics
googleAnalytics = "UA-1511XXXX-X"

enableRobotsTXT = true


[module]
[[module.mounts]]
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":fileModTime", ":default"]

sectionPagesMenu = "main"

[menu]

[[menu.main]]
    identifier = "books"
    title = "Books"
    url = "/books/"
    weight = 200

[[menu.main]]
    identifier = "research"
    title = "Research"
    url = "/research/"
    weight = 300